### PR TITLE
Feature/hourly forecast

### PR DESCRIPTION
**Pull request by troya2**
Added support for the hourly forecast in the pro 2.5 API

### CODE REVIEW

**Comment by dblock** [comment]
Very nice. Let's not drop Ruby 3.0 support here, put back those named parameters. Rubocop should also be targeting the correct version syntax.

**Comment by troya2** [comment]
Do you have any suggestions on getting my local environment in sync with the project's rubocop expectations?  I don't see .rubocop.yml in the project.  What's the best practice for that?

**Comment by dblock** [comment]
> Do you have any suggestions on getting my local environment in sync with the project's rubocop expectations? I don't see .rubocop.yml in the project. What's the best practice for that?

You shouldn't need to do anything. There's https://github.com/dblock/open-weather-ruby-client/blob/master/.rubocop.yml checked in here. If you run something in the project make sure to prefix it with `bundle exec ...` otherwise it may pickup a different version, maybe that's what's happening?

For this PR I would undo the automatic changes of those parameters/revert the files that were auto-edited, one-by-one.

**Comment by troya2** [comment]
I had to add a .ruby-version with an earlier version of ruby than my global version to get rubocop to prefer (named: named, parameters: parameters).

Would it make sense to add a .ruby-version to the repo and/or update .rubocop.yml to have a more complete set of style directives?

Also, assuming this is merged in, do you want me to do a release?  Sorry I didn't get to it before...

**Comment by dblock** [comment]
> Would it make sense to add a .ruby-version to the repo and/or update .rubocop.yml to have a more complete set of style directives?

Possibly. We test with multiple versions of Ruby, so maybe not a .ruby-version, but actually fixing rubocop violations and improving .rubocop.yml is always a great idea.

> Also, assuming this is merged in, do you want me to do a release? Sorry I didn't get to it before...

Absolutely.

**Review by dblock — APPROVED** [review]

**Pull request merged**
