### PR TITLE
Upgrade faraday to 2.x

### PR DESCRIPTION
**Pull request by dgarwood**

### CODE REVIEW

**Comment by dblock** [comment]
Let's bump to 0.4.0 as part of this PR?

Please check https://github.com/slack-ruby/slack-ruby-client/pull/406 and https://github.com/slack-ruby/slack-ruby-client/pull/434 that had to do more involved things for this upgrade. Looks like some error handling differences, etc. Also do we need something in UPGRADING.md?

**Comment by andreibondarev** [comment]
Any chance we can get this PR pushed through? We'd like to bump https://github.com/andreibondarev/langchainrb faraday to 2.x and this gem is one of the deps. Thank you!

**Comment by dblock** [comment]
I merged it, will increment the version and cut a release.

**Comment by dblock** [comment]
@andreibondarev And done, use 0.4.0.

**Pull request merged**
